name: Build and Publish Docker Image to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/delivery:latest .
      - name: Publish Image
        run: |
          docker login -u ${{ github.repository_owner }} -p ${{ secrets.GHCR_TOKEN }} ghcr.io
          docker push ghcr.io/${{ github.repository_owner }}/delivery:latest
