name: Build and Publish Docker Image to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/delivery:latest .
      - name: Publish Image
        run: |
          docker login -u ${{ github.repository_owner }} -p ${{ secrets.GHCR_TOKEN }} ghcr.io
          docker push ghcr.io/${{ github.repository_owner }}/delivery:latest
      - name: Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem root@165.232.171.38 "
            docker login -u ${{ github.repository_owner }} -p ${{ secrets.GHCR_TOKEN }} ghcr.io &&
            docker ps -aq | xargs docker stop | xargs docker rm &&
            docker run -d -p 8080:8080 ghcr.io/${{ github.repository_owner }}/delivery:latest"
