name: Build and Publish Docker Image to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true 
          tags: ghcr.io/${{ github.repository_owner }}/delivery:latest
      - name: Tag Docker image with commit SHA
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/delivery"
          COMMIT_SHA=$(git rev-parse --short HEAD)  # Get the commit SHA
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$COMMIT_SHA  # Tag with commit SHA
          docker push $IMAGE_NAME:$COMMIT_SHA  # Push the commit-tagged image
